import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Container } from '@/components/Container/Index'
import { Card } from '@/components/Card/Index'
import { Text } from '@/components/Text/Index'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Container>
          <Card customClase={"image-light"}>
            <Text text="the day"/>

          </Card>
          <Card>
            <Text text="the night"/>

          </Card>
        </Container>
      </main>
    </>
  )
}
